version: '3'
services:
  reverseproxy:
    build: ./nginx
    ports:
      - 80:80
    restart: always
  
  node:
    depends_on:
      - reverseproxy
    build: ./node
    restart: always
    links:
      - mongo

  mongo:
    image: mvertes/alpine-mongo
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017
    restart: always
